config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "products/my_products", to: "products#my_products", as: "my_products"
  get "products/categories/:category", to: "products#category", as: "category"
  get "transactions/shopping_list/", to: "transactions#shopping_list", as: "shopping_list"
  get "transactions/selling_list/", to: "transactions#selling_list", as: "selling_list"
  get "transactions/:id", to: "transactions#show", as: "transaction"
  post "transactions", to: "transactions#create"
  # get "transactions/:id", to: "transactions#show", as: ""
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :transactions
  belongs_to :user

  validates :name, :price, :expiration_date, :stock, presence: true
  validates :name, length: { minimum: 3 }
  validates :expiration_date, comparison: { greater_than_or_equal_to: Date.today }
  # validate :validate_date
  validates :price, numericality: { greater_than: 0 }
  CATEGORIES = %w[frescos procesados granos\ y\ cereales bebidas congelados panadería\ y\ repostería dietéticos\ y\ suplementos orgánicos vegetarianos\ y\ veganos]
  validates :category, inclusion: { in: CATEGORIES }

  has_one_attached :photo

  # def validate_date
  #   if expiration_date < Date.today
  #     "La fecha no puede ser menor a la actual"
  #   end
  # end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :products
  has_many :transactions
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @products = Product.all.sample(3)

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :category]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  def index
    @products = Product.where.not(user: current_user)
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to product_path(@product)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def my_products
    @products = Product.where(user: current_user)
  end

  def category
    @products = Product.where(category: params[:category])
  end

  def edit
  end

  def update
    @product.update(product_params)
    if @product.save
      redirect_to product_path(@product)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to my_products_path, status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:name, :stock, :price, :expiration_date, :photo, :category)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def shopping_list
    @compras = Transaction.where(user: current_user)
  end

  def selling_list
    @ventas = []
    Transaction.all.each do |transaction|
    @ventas << transaction if transaction.product.user == current_user
    end
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def create
    @product = Product.find(params[:product_id])
    Transaction.create(user: current_user, product: @product, price: @product.price)
    @product.stock -= 1
    @product.save
    redirect_to shopping_list_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GROCERYSaver</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Archivo+Black&family=Lato:wght@700&family=Roboto:wght@100;300;400;500;900&display=swap" rel="stylesheet">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= render "shared/footer" %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path 'banner_home.jpg' %>);">

  <div class="container">
    <h1><strong>SABOR DE CALIDAD</strong></h1>
    <h1><strong>HASTA EL ULTIMO</strong></h1>
    <h1><strong>SEGUNDO</strong></h1>
    <p>Cambia tu vida, cuidando el planeta.</p>
    <a class="btn btn-flat" href="#section-information">Conocer más</a>
  </div>
</div>

 <!--Prueba animacion-->

 <!-- <div class="word-rotator">
  <span><strong>CAMBIEMOS EL MUNDO JUNTOS, COMPRA CONSCIENTE</strong></span>
  <span>strAyudemos el planeta. Cero desperdicios </span>
</div> -->


  <!--Seccion de información-->

<div class="bg-white py-4 fondo-grocery">
  <div class="animacion">
    <div class="card-section-title text-center"><span class="green-text">2000 +</span> DESPERDICIOS MENOS EN EL MES</div>
  </div>

  <div class="container w-85 mb-5">
        <div class="row justify-content-center">

            <!-- Card 1 -->
            <div class="col-4" id="section-information">
                <h2><strong>TODOS JUNTOS POR</strong></h2>
                <h2><strong><span class="green-text">EL CERO DESPERDICIO</span></strong></h2>
            </div>

            <!-- Card 2 -->
            <div class="col-4 mr-5">
                <div class="intervalo-line">
                  <div class="card-title"><strong>Economía Conciente</strong></div>
                  <div class="card-description">Ahorra mientras haces una elección
                  inteligente. Nuestros productos, a punto de expirar, ofrecen
                  calidad a precios reducidos, beneficiando tanto a tu bolsillo
                  como al medio ambiente.</div>

                  <div class="card-title"><strong>Responsabilidad</strong></div>
                  <div class="card-description">El sabor no tiene fecha de vencimiento.
                  Ofrecemos productos que, aunque cercanos a expirar, mantienen toda su
                  frescura y sabor, asegurando una experiencia gastronómica deliciosa y
                  ética.</div>

                  <div class="card-title"><strong>Sostenibilidad</strong></div>
                  <div class="card-description">Creemos en un mundo donde el desperdicio es cero.
                  Al consumir alimentos cercanos a su fecha de vencimiento, estamos dando un
                  paso adelante hacia un planeta más sostenible y responsable.</div>
                </div>
            </div>
        </div>
  </div>



  <!--Categorias-->
  <div class="caja-categorias">
    <div class="container w-75 box-principal">


      <!--Categoria 1-->
      <div class="row d-flex justify-content-center mb-4">
        <div class="col-4 text-center d-flex flex-column">
          <div class="category-card">
            <i class="fas fa-apple-alt mb-2"></i>
            <%= link_to "FRESCOS", category_path("frescos"), class: "text-decoration-none text-dark fw-bold" %>
          </div>
        </div>

        <div class="col-4 text-center d-flex flex-column">
          <div class="category-card">
            <i class="fas fa-bacon mb-2"></i>
            <%= link_to "PROCESADOS", category_path("procesados"), class: "text-decoration-none text-dark fw-bold" %>
          </div>
        </div>

        <div class="col-4 text-center d-flex flex-column">
          <div class="category-card">
            <i class="fas fa-seedling"></i>
            <%= link_to "GRANOS Y CEREALES", category_path("granos y cereales"), class: "text-decoration-none text-dark fw-bold" %>
          </div>
        </div>
      </div>


      <!--Categoria 2-->
      <div class="row d-flex justify-content-center mb-4">
        <div class="col-4 text-center d-flex flex-column">
          <div class="category-card">
            <i class="fas fa-glass-martini mb-2"></i>
            <%= link_to "BEBIDAS", category_path("bebidas"), class: "text-decoration-none text-dark fw-bold" %>
          </div>
        </div>

        <div class="col-4 text-center d-flex flex-column">
          <div class="category-card">
            <i class="fas fa-fish mb-2"></i>
            <%= link_to "CONGELADOS", category_path("congelados"), class: "text-decoration-none fw-bold text-dark" %>
          </div>
        </div>

        <div class="col-4 text-center d-flex flex-column">
          <div class="category-card">
            <i class="fas fa-bread-slice"></i>
            <%= link_to "PANADERÍA Y REPOSTERÍA", category_path("panadería y repostería"), class: "text-decoration-none text-dark fw-bold" %>
          </div>
        </div>
      </div>

      <!--Categoria 3-->

      <div class="row d-flex justify-content-center">
        <div class="col-4 text-center d-flex flex-column ">
          <div class="category-card">
            <i class="fas fa-capsules mb-2"></i>
            <%= link_to "DIETÉTICOS Y SUPLEMENTOS", category_path("dietéticos y suplementos"), class: "text-decoration-none text-dark fw-bold" %>
          </div>
        </div>

        <div class="col-4 text-center d-flex flex-column">
          <div class="category-card">
            <i class="fas fa-leaf"></i>
            <%= link_to "ORGANICOS", category_path("orgánicos"), class: "text-decoration-none text-dark fw-bold" %>
          </div>
        </div>

        <div class="col-4 text-center d-flex flex-column">
          <div class="category-card">
            <i class="fas fa-walking mb-2"></i>
            <%= link_to "VEGETARIANOS Y VEGANOS", category_path("vegetarianos y veganos"), class: "text-decoration-none text-dark fw-bold" %>
          </div>
        </div>
      </div>
    </div>

  </div>

  <!--Card con informacion-->
<div class="container mt-5 mb-3">
  <div class="d-flex justify-content-center mb-3">
    <h1 class="text-center">PRODUCTOS DESTACADOS</h1>
  </div>
  <div class="d-flex flex-wrap justify-content-center g-3">
    <% @products.each do |product| %>


    <% if product.stock > 0 %>
      <div class="card bg-white m-3 p-1" style="width: 18rem; height: 30rem">
        <% if product.photo.key != nil %>
        <%= cl_image_tag(product.photo.key, height: 200, width: 200, crop: :pad, class: "mx-auto") %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= product.name %></h5>
          <p class="card-text">Fecha de vencimiento: <br> <%= product.expiration_date %></p>
          <p class="card-text">Precio: $<%= product.price %></p>
          <p class="card-text">Stock: <%= product.stock %></p>
          <div class="d-flex justify-content-between ">
            <h4><%= link_to "Ver producto", product_path(product.id), class: "btn btn-primary",
              style: "--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" %></h4>
            <h4><%= button_to "Comprar", transactions_path(product_id: product.id), class: "btn btn-primary",
              style: "--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" %></h4>
          </div>
        </div>
    </div>

    <% end %>
    <% end %>
  </div>
</div>

app/views/products/_form.html.erb
  <%= simple_form_for @product do |f| %>
<div class="row mt-3">
  <div class="col-6">
    <%= f.input :name %>
    <%= f.input :stock %>
  </div>
  <div class="col-6">
    <%= f.input :price %>
    <%= f.input :category, collection: Product::CATEGORIES %>
  </div>
  </div>
  <div class="row">
    <%= f.input :expiration_date %>
    <%= f.input :photo, as: :file %>
  </div>
  <div class="row justify-content-center">
    <div class="col">
    <%= f.button :submit %>
    </div>
  </div>
    <% end %>

app/views/products/category.html.erb
<div class="container mt-5 mb-3">
  <% if @products.size > 0 %>
    <div class="d-flex justify-content-between mb-3">
      <h1><%= @products.first.category.upcase %></h1>
    </div>
    <div class="d-flex flex-wrap justify-content-center g-3">
      <% @products.each do |product| %>
      <% if product.stock > 0 %>
      <div class="card bg-white m-3 p-1" style="width: 18rem; height: 30rem">
        <% if product.photo.key != nil %>
        <%= cl_image_tag(product.photo.key, height: 200, width: 200, crop: :pad, class: "mx-auto") %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= product.name %></h5>
          <p class="card-text">Fecha de vencimiento: <br> <%= product.expiration_date %></p>
          <p class="card-text">Precio: $<%= product.price %></p>
          <p class="card-text">Stock: <%= product.stock %></p>
          <div class="d-flex justify-content-between ">
            <h4><%= link_to "Ver producto", product_path(product.id), class: "btn btn-primary",
              style: "--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" %></h4>
            <h4><%= button_to "Comprar", transactions_path(product_id: product.id), class: "btn btn-primary",
              style: "--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" %></h4>
        </div>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  <% else %>
    <p>No hay productos de esta categoría</p>
  <% end %>
</div>

app/views/products/edit.html.erb
<div class="container mt-5 mb-3">
<h1>EDITAR PRODUCTO</h1>
<div class="row justify-content-center">
  <div class="col-8">
    <%= render "form" %>
  </div>
</div>


</div>

app/views/products/index.html.erb
<div class="container mt-5 mb-3">
  <div class="d-flex justify-content-start mb-3">
    <h1>TODOS LOS PRODUCTOS</h1>
  </div>
  <div class="d-flex flex-wrap justify-content-center g-3">
    <% @products.each do |product| %>


    <% if product.stock > 0 %>
      <div class="card bg-white m-3 p-1" style="width: 18rem; height: 30rem">
        <% if product.photo.key != nil %>
        <%= cl_image_tag(product.photo.key, height: 200, width: 200, crop: :pad, class: "mx-auto") %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= product.name %></h5>
          <p class="card-text">Fecha de vencimiento: <br> <%= product.expiration_date %></p>
          <p class="card-text">Precio: $<%= product.price %></p>
          <p class="card-text">Stock: <%= product.stock %></p>
          <div class="d-flex justify-content-between ">
            <h4><%= link_to "Ver producto", product_path(product.id), class: "btn btn-primary",
              style: "--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" %></h4>
            <h4><%= button_to "Comprar", transactions_path(product_id: product.id), class: "btn btn-primary",
              style: "--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" %></h4>
          </div>
        </div>
    </div>

    <% end %>
    <% end %>
  </div>
</div>

app/views/products/my_products.html.erb
<div class="container mt-5 mb-3">
  <div class="d-flex justify-content-between align-items-center m-3">
    <h1>MIS PRODUCTOS</h1>
    <%= link_to "Agregar producto", new_product_path, class:"btn btn-primary"%>
  </div>
  <div class="d-flex flex-wrap justify-content-center g-3">
    <% if @products.size > 0 %>
      <% @products.each do |product| %>
      <% if product.stock > 0 %>
        <div class="card bg-white m-3 p-1" style="width: 18rem; height: 30rem">
          <% if product.photo.key != nil %>
            <%= cl_image_tag(product.photo.key, height: 200, width: 200, crop: :pad, class: "mx-auto") %>
            <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= product.name %></h5>
          <p class="card-text">Fecha de vencimiento: <br> <%= product.expiration_date %></p>
          <p class="card-text">Precio: $<%= product.price %></p>
          <p class="card-text">Stock: <%= product.stock %></p>
          <%= link_to '<i class="fa-solid fa-trash "></i>'.html_safe, product_path(product.id),
            class: "position-icon",
            data: {turbo_method: :delete, turbo_confirm: "¿Seguro que quieres borrar este producto?"} %>
          <div class="d-flex justify-content-between ">
            <h4><%= link_to "Ver producto", product_path(product.id), class: "btn btn-primary",
              style: "--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" %></h4>
            <h4><%= link_to "Editar", edit_product_path(product.id), class: "btn btn-primary",
              style: "--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" %></h4>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
    <% else %>
    <p>No hay productos disponibles</p>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container mt-5 mb-3">
<div class="m-3">
<h1>AGREGAR PRODUCTO</h1>
  <div class="row justify-content-center">
  <div class="col-8">
    <%= render "form" %>
  </div>
</div>


</div>


</div>

app/views/products/show.html.erb
<div class="container mt-5 mb-3">
  <div class="d-flex justify-content-start mb-3">
    <h1>DETALLES DEL PRODUCTO</h1>
  </div>
  <div class="d-flex flex-row mb-3 justify-content-center">
    <div class="card mb-3" style="width: 50rem;">
      <div class="row g-0">
        <div class="col-md-4 bg-white align-items-center d-flex">
          <% if @product.photo.key != nil %>
          <%= cl_image_tag(@product.photo.key, crop: :fill,
          class: "img-fluid rounded-start") %>
          <% end %>
        </div>
        <div class="col-md-8 ps-3">
          <div class="card-body">
            <h5 class="card-title"><%= @product.name %></h5>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Fecha de vencimiento: <strong><%=@product.expiration_date %></strong></li>
              <li class="list-group-item">Categoría: <%=@product.category.capitalize %></li>
              <li class="list-group-item">Precio: $<%=@product.price %></li>
              <li class="list-group-item">Stock: <%=@product.stock %></li>
              <li class="list-group-item">Vendedor: <%=@product.user.email %></li>
            </ul>
          </div>
          <div class="d-flex justify-content-start ms-3 mb-3 ps-3">
            <% if @product.user == current_user %>
            <%= link_to "Editar", edit_product_path(@product.id), class: "btn btn-primary" %>
            <% end %>
            <% if current_user != @product.user %>
            <%= button_to "Comprar", transactions_path(product_id: @product.id), class: "btn btn-primary" %>
            <% end %>
            <%= link_to "Volver", products_path, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_buttom.html.erb
 <a class="btn btn-flat" href="#">Conocer más</a>

app/views/shared/_footer.html.erb
<footer class= "mt-5 position-absolute">
        <div class="footer-section">
          <div class="footer-logo">
            <%= image_tag("LOGO.png") %>
          </div>
        </div>
        <div class="footer-section">
            <p><strong>Ubicación:</strong> Chile, México, Argentina</p>
            <p><strong>Teléfono:</strong> +123-456-7890</p>
        </div>
        <div class="footer-section">
            <a href="#">Política de Privacidad</a>
            <a href="#">Términos y Condiciones</a>
            <a href="#">Contáctanos</a>
        </div>
        <div class="footer-section footer-links">
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
        </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid mt-0">
    <%= link_to root_path, class: "navbar-brand ms-3" do %>
      <%= image_tag("Logo_grocery_saver.png") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link color-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Productos", products_path , class: "nav-link color-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" id= "dropdown-title"class="nav-link" id="categoryDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categorias
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Frescos", category_path("frescos"), class: "dropdown-item" %>
              <%= link_to "Procesados", category_path("procesados"), class: "dropdown-item" %>
              <%= link_to "Granos y Cereales", category_path("granos y cereales"), class: "dropdown-item" %>
              <%= link_to "Bebidas", category_path("bebidas"), class: "dropdown-item" %>
              <%= link_to "Congelados", category_path("congelados") , class: "dropdown-item" %>
              <%= link_to "Panaderia y Reposteria", category_path("panadería y repostería"), class: "dropdown-item" %>
              <%= link_to "Dieteticos y Suplementos", category_path("dietéticos y suplementos") , class: "dropdown-item" %>
              <%= link_to "Organicos", category_path("orgánicos"), class: "dropdown-item" %>
              <%= link_to "Vegetarianos y Veganos", category_path("vegetarianos y veganos"), class: "dropdown-item" %>
            </div>
          </li>
          <% if user_signed_in? == false %>
          <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link nav-link-login" %>
          <% else %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             <% if current_user.photo %>
             <%= cl_image_tag(current_user.photo.key, :transformation=>[
                {:gravity=>"face", :height=>400, :width=>400, :crop=>"crop"},
                {:radius=>"max"},
                {:width=>40, :crop=>"scale"},
                {:fetch_format=>:auto}
                ])  %>
             <% else %>
            <%= image_tag "avatar.svg", class: "avatar", alt: "dropdown menu" %>
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mis compras", shopping_list_path , class: "dropdown-item" %>
              <%= link_to "Mis ventas", selling_list_path , class: "dropdown-item" %>
              <%= link_to "Mis Productos", my_products_path , class: "dropdown-item" %>
              <%= link_to "Agregar productos", new_product_path , class: "dropdown-item" %>

              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/transactions/selling_list.html.erb
<div class="container my-5">
<div class="row justify-content-center">
<div class="col-8">
 <h1>MIS VENTAS</h1>
</div>

</div>

    <% @ventas.each do |venta| %>
    <div class="row justify-content-center">
      <div class="col-8">
       <div class="card p-1 w-100 m-2">
        <div class="card-header fondo-header">
          Fecha: <%= venta.created_at.strftime("%d/%m/%Y") %>
        </div>
        <div class="card-body d-flex justify-content-between align-items-center">
        <div class='d-flex align-items-center'>
          <p class="card-text fw-semibold mb-0 me-5"><%= venta.product.name %></p>
          <p class="card-text align-self-end">Precio: $<%= venta.product.price %></p>
        </div>
          <%= link_to "Ver venta", transaction_path(venta.id), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
</div>

app/views/transactions/shopping_list.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-8">
      <h1>MIS COMPRAS</h1>
    </div>
  </div>


    <% @compras.each do |compra| %>
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="card p-1 w-100 m-2">
        <div class="card-header fondo-header">
          Fecha: <%= compra.created_at.strftime("%d/%m/%Y") %>
        </div>
        <div class="card-body d-flex justify-content-between align-items-center">
        <div class='d-flex align-items-center'>
          <p class="card-text fw-semibold mb-0 me-5"><%= compra.product.name %></p>
          <p class="card-text align-self-end ">Precio: $<%= compra.product.price %></p>
        </div>
          <%= link_to "Ver compra", transaction_path(compra.id), class: "btn btn-primary" %>
        </div>
       </div>
      </div>
    </div>
    <% end %>
  </div>

app/views/transactions/show.html.erb
<div class="container mt-5 mb-3">
  <div class="d-flex justify-content-start mb-3">
    <h1>DETALLES DE TRANSACCIÓN</h1>
  </div>
  <div class="d-flex flex-row mb-3 justify-content-center">
    <div class="card mb-3" style="width: 50rem;">
      <div class="row g-0">
        <div class="col-md-4 align-items-center d-flex bg-white">
          <% if @transaction.product.photo.key != nil %>
          <%= cl_image_tag(@transaction.product.photo.key, crop: :fill,
          class: "img-fluid rounded-start") %>
          <% end %>
        </div>
        <div class="col-md-8 ps-3">
          <div class="card-body">
            <h5 class="card-title"><%= @transaction.product.name %></h5>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Fecha de compra: <strong><%=@transaction.created_at %></strong></li>
              <% if @transaction.user != current_user %>
              <li class="list-group-item">Comprador: <%=@transaction.user.email %></li>
              <% else %>
              <li class="list-group-item">Vendedor: <%=@transaction.product.user.email %></li>
              <% end %>
              <li class="list-group-item">Precio: $<%=@transaction.product.price %></li>
            </ul>
          </div>
          <div class="d-flex justify-content-start ms-3 mb-3 ps-3">
            <% if @transaction.user != current_user %>
            <%= link_to "Volver", selling_list_path, class: "btn btn-primary" %>
            <% else %>
            <%= link_to "Volver", shopping_list_path, class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>